import Foundation
import simd

/// Eight studies in the same metre-scale Chicago world as Willis and the park.
enum LakefrontScene {
    static let stops: [TourStop] = [
        TourStop(id: 0, title: "The Magnificent Mile", subtitle: "NORTH MICHIGAN AVENUE · A CITY OF LANDMARKS", detail: "Travel north above Michigan Avenue from the river's architectural gateway toward the Water Tower district. Mapped building footprints and heights establish the street, with storefronts, stonework and towers articulated around the route.", pose: CameraPose(position: SIMD3(972,88,-1080), target: SIMD3(978,100,-1410), fov: 65)),
        TourStop(id: 1, title: "A survivor in limestone", subtitle: "THE HISTORIC CHICAGO WATER TOWER · 1869", detail: "Walk around the castellated limestone Water Tower, a survivor of the Great Chicago Fire. Turrets, Gothic openings and stone courses sit beside the historic pumping station, surrounded by the modern city.", pose: CameraPose(position: SIMD3(975,1.8,-2008), target: SIMD3(951.6,22,-2036.52), fov: 80)),
        TourStop(id: 2, title: "Water Tower Place", subtitle: "MICHIGAN AVENUE · SHOPS, STONE & GLASS", detail: "Follow the retail frontage beneath the Water Tower Place tower. Study the podium's marble-toned panels, recessed glazing and entrances before looking upward to the stepped high-rise above.", pose: CameraPose(position: SIMD3(977,2,-2076), target: SIMD3(1030,50,-2132), fov: 82)),
        TourStop(id: 3, title: "The Hancock's great diagonals", subtitle: "875 NORTH MICHIGAN AVENUE · A BRACED TUBE", detail: "Rise beside the former John Hancock Center's tapered dark tower. Its monumental X braces, recessed curtain wall, mechanical bands and twin antennas define one of Chicago's most recognizable silhouettes.", pose: CameraPose(position: SIMD3(1355,272,-2004), target: SIMD3(1062.85,245,-2219.95), fov: 70)),
        TourStop(id: 4, title: "Buckingham Fountain", subtitle: "GRANT PARK · WATER, BRONZE & PINK MARBLE", detail: "Approach the fountain's broad basin, sculptural tiers and water jets within Grant Park's formal landscape. After dark, illuminated water reflects across the pool beneath the skyline.", pose: CameraPose(position: SIMD3(1319,19,422), target: SIMD3(1404.55,6,342.20), fov: 59)),
        TourStop(id: 5, title: "Chicago's front yard", subtitle: "GRANT PARK · GARDENS & THE SKYLINE", detail: "Move above the park's mapped lawns, formal paths and planting toward Buckingham Fountain and the city skyline. Benches, garden edges and nearby architecture provide a sense of scale within the larger landscape.", pose: CameraPose(position: SIMD3(1540,24,560), target: SIMD3(1230,35,75), fov: 61)),
        TourStop(id: 6, title: "Harbors on Lake Michigan", subtitle: "DUSABLE & MONROE · SAILBOATS AND THE CITY", detail: "Explore the lakefront's marina piers and moored boats. Detailed hulls, cabins, masts and rigging sit on reflective water, with the skyline and harbor lights visible beyond the berths.", pose: CameraPose(position: SIMD3(2135,6,-585), target: SIMD3(2020,-2,-680), fov: 61)),
        TourStop(id: 7, title: "Along Lake Shore Drive", subtitle: "THE LAKEFRONT · A TWO-MINUTE FLIGHT", detail: "Follow the curve of DuSable Lake Shore Drive beside Lake Michigan, passing light traffic, beaches and harbors toward Grant Park. Moving vehicles participate in the ray-traced scene, including reflections and shadows.", pose: CameraPose(position: SIMD3(1032,75,-2870), target: SIMD3(1170,12,-2460), fov: 65))
    ]
}
