import Foundation
import simd

/// Eight connected studies south of Grant Park in the resident Chicago world.
enum MuseumCampusScene {
    static let stops: [TourStop] = [
        TourStop(id:0,title:"From art to natural history",subtitle:"ART INSTITUTE → FIELD MUSEUM · THREE-MINUTE FLIGHT",detail:"Continue south from the Art Institute across Grant Park and Buckingham Fountain to the Field Museum. The route descends to its north portico and enters the great hall in the same continuous Chicago world.",pose:CameraPose(position:SIMD3(1246,68,-130),target:SIMD3(1088,15,-145),fov:65)),
        TourStop(id:1,title:"The Field Museum",subtitle:"WHITE MARBLE · STANLEY FIELD HALL",detail:"Climb the monumental north entrance and walk into the tall, skylit hall. Ionic columns, gallery balustrades and a modeled prehistoric skeleton give scale to an interpretation of the museum's principal public interior.",pose:CameraPose(position:MuseumBuildingsLayout.fieldRoute[0],target:MuseumBuildingsLayout.fieldPoint(SIMD3(0,17,-47)),fov:74)),
        TourStop(id:2,title:"A world beneath the water",subtitle:"SHEDD AQUARIUM · ROTUNDA & OCEANARIUM",detail:"Enter the marble aquarium and pass between the freshwater and saltwater habitats beneath the rotunda's golden crown. Continue toward the lake-facing oceanarium through selected interpreted public spaces.",pose:CameraPose(position:MuseumBuildingsLayout.sheddRoute[0],target:MuseumBuildingsLayout.sheddPoint(SIMD3(-10,12,0)),fov:70)),
        TourStop(id:3,title:"Adler at the edge of the lake",subtitle:"GRANITE · COPPER · A JOURNEY INTO THE DOME",detail:"Approach the planetarium's twelve-sided granite core and copper dome, then explore its gallery and enter the theater. Exhibit models and the immersive sky program are original interpretations within the mapped building envelope.",pose:CameraPose(position:AdlerLayout.center+SIMD3(-52,1.8,1.5),target:AdlerLayout.center+SIMD3(0,15,0),fov:67)),
        TourStop(id:4,title:"A sky made of light",subtitle:"INSIDE THE PLANETARIUM · AN ORIGINAL DOME SHOW",detail:"Glide into the clear central aisle beneath a 21-metre projection dome. Stars, constellations, aurora ribbons and planetary arcs evolve overhead. Play, pause and rewind control the show and camera together.",pose:CameraPose(position:AdlerLayout.theaterCenter+SIMD3(-1.1,0,-0.6),target:AdlerLayout.theaterLook,fov:98)),
        TourStop(id:5,title:"Soldier Field",subtitle:"HISTORIC COLONNADES · A MODERN BOWL",detail:"Circle the stadium's classical stone colonnades and rise over the modern seating bowl. The field, terraces, entrances and surrounding park share their mapped positions with the museums and harbor.",pose:CameraPose(position:SIMD3(1775,57,1670),target:SIMD3(1592,19,1825),fov:67)),
        TourStop(id:6,title:"Boats in Burnham Harbor",subtitle:"PIERS · MASTS · THE SOUTH LAKEFRONT",detail:"Travel above the marina's mapped water and piers among detailed moored boats. The museum skyline, Northerly Island and the city frame reflective water and harbor lighting after dark.",pose:CameraPose(position:SIMD3(2180,30,1870),target:SIMD3(1990,-2,2020),fov:65)),
        TourStop(id:7,title:"The McCormick Place campus",subtitle:"FOUR GREAT HALLS · BRIDGES, HOTELS & ROOF GARDENS",detail:"Explore Lakeside, North, South and West in one three-minute flight. Cable-supported roofs, the Grand Concourse, glass skywalks and planted terraces connect the convention buildings, hotels and Wintrust Arena.",pose:McCormickLayout.stop)
    ]
}
