import Foundation
import simd

/// Eight studies in the continuous Chicago landscape, from the Loop to Wrigleyville.
enum NorthSideScene {
    static let stops:[TourStop] = [
        TourStop(id:0,title:"From Millennium Park to the zoo",subtitle:"THE NORTH LAKEFRONT · FOUR-MINUTE FLIGHT",detail:"Leave Millennium Park, follow the river and the city’s northern shoreline, then descend toward Lincoln Park’s South Pond. The downtown skyline, beaches and zoo remain in one continuous Chicago world.",pose:CameraPose(position:SIMD3(1230,120,-570),target:SIMD3(1030,10,-520),fov:67)),
        TourStop(id:1,title:"The streets of Old Town",subtitle:"ST. MICHAEL’S · WELLS STREET · NEIGHBORHOOD ROOFLINES",detail:"Explore the red-brick church and its tall clock spire, then follow the scale and texture of Old Town’s streets. Mapped row houses, cornices, shopfronts and leafy blocks bridge the skyline and Lincoln Park.",pose:CameraPose(position:SIMD3(-445,28,-3870),target:SIMD3(-399,36,-3756),fov:66)),
        TourStop(id:2,title:"A ship beside the lake",subtitle:"NORTH AVENUE BEACH · SAND, BLUE RAILINGS & SKYLINE",detail:"Circle the ocean-liner-inspired beach house and travel along the promenade. Rounded white walls, blue portholes, upper decks and red funnels overlook the mapped beach and Lake Michigan.",pose:CameraPose(position:NorthSideLandmarksLayout.beachPoint(SIMD3(-68,24,42)),target:NorthSideLandmarksLayout.beachPoint(SIMD3(4,4,-8)),fov:65)),
        TourStop(id:3,title:"South Pond and the Nature Boardwalk",subtitle:"CAFÉ BRAUER · TIMBER LATTICE · WATER & REEDS",detail:"Walk through the pavilion’s curved timber lattice and along the South Pond boardwalk. Café Brauer, reflected trees and the city skyline frame the water; an authored seasonal lighting composition adds color after dark.",pose:CameraPose(position:LincolnParkZooLayout.natureStart,target:LincolnParkZooLayout.pavilionCenter+SIMD3(0,3.8,0),fov:76)),
        TourStop(id:4,title:"A walk through Lincoln Park Zoo",subtitle:"HISTORIC HOUSES · HABITATS · A GARDEN OF LIGHT",detail:"Follow the zoo’s public mall past historic animal houses and interpreted habitats. Night lighting takes inspiration from ZooLights, with warm entrances and carefully grouped colored trees and arches, rather than a recreation of a particular year’s display.",pose:CameraPose(position:LincolnParkZooLayout.zooStart,target:SIMD3(242,5,-4690),fov:74)),
        TourStop(id:5,title:"Glasshouses and the lily pool",subtitle:"LINCOLN PARK CONSERVATORY · ALFRED CALDWELL’S GARDEN",detail:"Move among the conservatory’s glass roofs and planted grounds toward the quiet lily pool. The mapped garden setting, stone edges, pavilion forms and layered foliage provide a more intimate view of Lincoln Park.",pose:CameraPose(position:LincolnParkZooLayout.conservatoryStart,target:LincolnParkZooLayout.conservatory+SIMD3(0,9,0),fov:73)),
        TourStop(id:6,title:"From the zoo to Wrigley Field",subtitle:"LINCOLN PARK · HARBORS · WRIGLEYVILLE",detail:"Rise from Lincoln Park, follow the lakefront toward Diversey and Belmont harbors, then turn inland across the North Side to Wrigley Field. The flight stays inside the same continuous Chicago landscape.",pose:CameraPose(position:SIMD3(435,100,-4670),target:SIMD3(234,9,-4710),fov:66)),
        TourStop(id:7,title:"Wrigley Field under the lights",subtitle:"THE FRIENDLY CONFINES · GALLAGHER WAY · WRIGLEYVILLE",detail:"Explore the ballpark’s red marquee, green scoreboard, ivy-covered brick walls, seating decks and surrounding rooftops. Broad white field lighting, warm streets and restrained red-and-blue accents shape the evening scene.",pose:CameraPose(position:SIMD3(-1776,74,-7578),target:SIMD3(-1640,9,-7710),fov:60))
    ]
}
