#!/usr/bin/env python3
"""Derive metre-scale zoo outlines/path exclusions from the checked-in OSM snapshot."""
import json, math, pathlib
root=pathlib.Path(__file__).resolve().parents[1]
raw=json.loads((root/'scripts/data/chicago-north-side-osm-2026-09-08.json').read_text())
data=json.loads((root/'scripts/data/chicago-north-side-landmarks-2026-09-08.json').read_text())
ids=[24826112,186667195,23986733,210686223,992815961,210686220,24826074,210685702,210686226,210686225,210686219,116740882,-2514193]
shapes={s['id']:s for s in data['landmarks']};scale=111320*math.cos(math.radians(41.878876))
def coords(e):return [((n['lon']+87.635918)*scale,(41.878876-n['lat'])*111320) for n in e.get('geometry',[])]
def vec2(p):return '['+','.join('SIMD2<Float>(%.3f,%.3f)'%(x,z) for x,z in p)+']'
def vec3(p,y):return '['+','.join('SIMD3<Float>(%.3f,%.3f,%.3f)'%(x,y,z) for x,z in p)+']'
text='''import Foundation
import simd

/// Generated by scripts/prepare-lincoln-park-zoo-map.py from OSM 2026-09-08.
/// © OpenStreetMap contributors, ODbL1.0. See docs/LINCOLN-PARK-ZOO.md.
enum LincolnParkZooMap {
    struct Shape {
        let id: Int64
        let points: [SIMD2<Float>]
        let triangles: [Int]
        let rings: [[SIMD2<Float>]]
    }
    struct Path { let id: Int64; let points: [SIMD3<Float>] }
    struct Road { let id: Int64; let halfWidth: Float; let points: [SIMD3<Float>] }
    static let shapes: [Shape] = [
'''
for id in ids:
 s=shapes[id]
 text+='        Shape(id:%d, points:%s, triangles:%s, rings:[%s]),\n'%(id,vec2(s['points']),str(s['triangles']),','.join(vec2(r) for r in s['rings']))
text+='    ]\n    static func shape(_ id:Int64) -> Shape { shapes.first { $0.id == id }! }\n    static let boardwalks: [Path] = [\n'
for e in raw['elements']:
 if e['type']!='way' or e.get('tags',{}).get('bridge')!='boardwalk':continue
 pts=coords(e)
 if pts and all(120<x<425 and -4530<z<-4160 for x,z in pts):text+='        Path(id:%d, points:%s),\n'%(e['id'],vec3(pts,.12))
text+='    ]\n    // All mapped public circulation, including paths outside the tour.\n    static let publicPaths: [Path] = [\n'
for e in raw['elements']:
 t=e.get('tags',{});pts=coords(e)
 if e['type']=='way' and t.get('highway') in ['footway','pedestrian','path','steps','cycleway'] and pts and any(0<x<435 and -5230<z<-4150 for x,z in pts):text+='        Path(id:%d, points:%s),\n'%(e['id'],vec3(pts,0))
text+='    ]\n    // Ancillary buildings remain context-owned; planting respects them too.\n    static let allBuildingRings: [[SIMD2<Float>]] = [\n'
for e in raw['elements']:
 t=e.get('tags',{});pts=coords(e)
 if e['type']=='way' and t.get('building') not in [None,'no'] and len(pts)>3 and any(0<x<435 and -5230<z<-4150 for x,z in pts):text+='        '+vec2(pts[:-1] if pts[0]==pts[-1] else pts)+',\n'
text+='    ]\n    // Same mapped centerlines and carriageway widths as the rendered context.\n    static let roads: [Road] = [\n'
roads={}
for resource in ['Chicago/ChicagoContext.json','Lakefront/LakefrontContext.json','NorthSide/NorthSideContext.json']:
 for road in json.loads((root/'Sources/ArchitectureEngine/Resources'/resource).read_text()).get('paths',[]):
  if road['kind'] not in ['footway','pedestrian','path','steps','cycleway'] and any(0<x<435 and -5230<z<-4150 for x,z in road['points']):roads[road['id']]=road
for id,road in sorted(roads.items()):text+='        Road(id:%d, halfWidth:%.3f, points:%s),\n'%(id,road['width']/2,vec3(road['points'],0))
text+='    ]\n}\n'
(root/'Sources/ArchitectureEngine/LincolnParkZooMap.swift').write_text(text)
print('Generated',len(text),'bytes of mapped zoo geometry and circulation exclusions')
